// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC_A1fHgyTiihuLYMBhizrwGvR7HoSo64',
    appId: '1:808655254753:web:0273051b9b46fc0330f3a0',
    messagingSenderId: '808655254753',
    projectId: 'caretalk-5efcb',
    authDomain: 'caretalk-5efcb.firebaseapp.com',
    databaseURL: 'https://caretalk-5efcb-default-rtdb.firebaseio.com',
    storageBucket: 'caretalk-5efcb.firebasestorage.app',
    measurementId: 'G-MV5W7T0H25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKCDJh5fqSco8DRVy7IPNTsT1zSVbmWA8',
    appId: '1:808655254753:android:f09b5b07f3cb750f30f3a0',
    messagingSenderId: '808655254753',
    projectId: 'caretalk-5efcb',
    databaseURL: 'https://caretalk-5efcb-default-rtdb.firebaseio.com',
    storageBucket: 'caretalk-5efcb.firebasestorage.app',
  );
}
